language: php
php:
  - 5.6
  - 7.0
  - 7.1
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  
script: phpunit --bootstrap vendor/autoload.php tests

notifications:
    on_success: never
    on_failure: always 
