<?php

namespace RandData\Set;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-09 at 21:49:59.
 */
class ComplexTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Complex
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Complex;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\Complex::get
     */
    public function testGet() {
        $obj1 = new Complex($this->getTpl());
        $this->assertRegExp($this->getPattern(), $obj1->get());
    }

    /**
     * @covers RandData\Set\Complex::init
     */
    public function testInit() {
        $params = [
            "template" => $this->getTpl()
        ];
        
        $obj1 = new Complex();
        $obj1->init($params);
        $this->assertRegExp($this->getPattern(), $obj1->get());
    }
    
    private function getPattern()
    {
        return "/^Hello, I'm (Peter|James|John), my age is ([\d]{2})$/i";
    }
    
    private function getTpl()
    {
        return "Hello, I'm {string_list:values=Peter,James,John}, my age is {integer:min=10;max=30}";
    }
}
