<?php

namespace RandData\Set;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-25 at 11:01:53.
 */
class NullValueTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var NullValue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NullValue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\NullValue::init
     */
    public function testInit() {
        $obj = new NullValue();

        for ($i = 1; $i <= 10; $i++) {
            $randValue = $this->object->get();
            $this->assertNull($randValue);
        }        
        
        $obj->init([ "key1" => 123, "key2" => "abc" ]);
        
        for ($i = 1; $i <= 10; $i++) {
            $randValue = $this->object->get();
            $this->assertNull($randValue);
        }        
    }

    /**
     * @covers RandData\Set\NullValue::get
     */
    public function testGet() {
        for ($i = 1; $i <= 10; $i++) {
            $randValue = $this->object->get();
            $this->assertNull($randValue);
        }
    }

}
