<?php

namespace RandData\Set;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-26 at 15:34:42.
 */
class StringListTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var StringList
     */
    protected $object;
    protected $values;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->values = [ "one", "two", "three", "four", "five", "six" ];
        $this->object = new StringList($this->values);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\StringList::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        for ($i = 1; $i <= 10; $i++) {
            $this->assertTrue(in_array($this->object->get(), $this->values));
        }
    }

    /**
     * @covers RandData\Set\StringList::init
     * @todo   Implement testInit().
     */
    public function testInit() 
    {
        $this->assertEquals($this->values, $this->object->getValues());
        $values =[
            "John",
            "Paul",
            "George",
            "Ringo"
        ];
        
        $params = [
            "values" => $values
        ];
        
        $this->object->init($params);
        $this->assertEquals($values, $this->object->getValues());
    }

}
