<?php

namespace RandData\Set;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-03 at 00:46:39.
 */
class ValueTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Value
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Value();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\Value::__construct
     * @covers RandData\Set\Value::get
     */
    public function testGet() {
        $this->assertEquals("", $this->object->get());
        $val = "abc";
        $obj2 = new Value($val);
        $this->assertEquals($val, $obj2->get());
    }

    /**
     * @covers RandData\Set\Value::init
     */
    public function testInit() {
        $val = "abc";
        $obj = new Value();
        $this->assertEquals("", $obj->get());
        $obj->init([ "value" => $val ]);
        $this->assertEquals($val, $obj->get());
    }
}
