<?php

namespace RandData\Set\en_GB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-10 at 21:55:09.
 */
class AddressTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Address
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Address;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\en_GB\Address::get
     */
    public function testGet() {
        $pattern = "/^[\d]{1,3}[a-f]?\s" . Street::VALIDATE_PATTERN . ",\s" 
                . City::VALIDATE_PATTERN . ", " . Postcode::VALIDATE_PATTERN . "$/";
        
        for ($i = 1; $i <= 10; $i++) {
            $value = $this->object->get();
            $this->assertNotEmpty($value);
            $this->assertRegExp($pattern, $value);
        }
    }
}
