<?php

namespace RandData\Set\en_GB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-10 at 21:55:23.
 */
class CityTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var City
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new City;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\en_GB\City::get
     */
    public function testGet() {
        $pattern = "/^" . City::VALIDATE_PATTERN . "$/";
        
        for ($i = 1; $i <= 10; $i++) {
            $value = $this->object->get();
            $this->assertNotEmpty($value);
            $this->assertRegExp($pattern, $value);
        }
    }

    /**
     * @covers RandData\Set\en_GB\City::init
     */
    public function testInit() {
        $pattern = "/^(Harrogate|Knaresborough|Ripon)$/";
        $this->object->init([ "postcode" => "HG" ]);
        
        for ($i = 1; $i <= 10; $i++) {
            $value = $this->object->get();
            $this->assertNotEmpty($value);
            $this->assertRegExp($pattern, $value);
        }
    }
}
