<?php

namespace RandData\Set\en_GB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-10 at 21:55:29.
 */
class PostcodeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Postcode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Postcode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\en_GB\Postcode::get
     * @covers RandData\Set\en_GB\Postcode::getPostcodeDistrictList
     * @covers RandData\Set\en_GB\Postcode::getInwardCode
     * @covers RandData\Set\en_GB\Postcode::getOutwardCode
     */
    public function testGet() {
        $pattern = "/^" . Postcode::VALIDATE_PATTERN . "$/";
        
        for ($i = 1; $i <= 10; $i++) {
            $val = $this->object->get();
            $this->assertNotEmpty($val);
            $this->assertRegExp($pattern, $val);
        }
    }
}
