<?php

namespace RandData\Set\en_GB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-10 at 21:55:34.
 */
class StreetTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Street
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Street;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\en_GB\Street::get
     */
    public function testGet() {
        for ($i = 1; $i <= 10; $i++) {
            $res = $this->object->get();
            $this->assertNotEmpty($res);
            $this->assertRegExp("/^" . Street::VALIDATE_PATTERN . "$/", $res);
        }
    }
}
