<?php

namespace RandData\Fabric\Tuple;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-23 at 21:47:04.
 */
class SqlCreateParserFabricTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SqlCreateParserFabric
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SqlCreateParserFabric;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Fabric\Tuple\SqlCreateParserFabric::create
     * @covers RandData\Fabric\Tuple\SqlCreateParserFabric::runParser
     */
    public function testCreateNull() {
        $this->assertNull($this->object->create("abc"));
    }
    
    /**
     * @covers RandData\Fabric\Tuple\SqlCreateParserFabric::create
     * @covers RandData\Fabric\Tuple\SqlCreateParserFabric::runParser
     */
    public function testCreate()
    {
        $res = $this->object->create("`sum_si` int(8) DEFAULT NULL");
        $this->assertEquals("integer:min=-1073741823;max=1073741823", $res);
    }
}
