<?php

namespace RandData\Fabric\Tuple;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-20 at 00:17:27.
 */
class SqlCreateTableTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SqlCreateTable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SqlCreateTable($this->getSql());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testGetFieldsAsSql()
    {
        $expected = [
            "`id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT",
            "`operator_id` smallint(5) unsigned DEFAULT NULL",
            "`manager_id` smallint(5) DEFAULT NULL",
            "`phone` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL",
            "`phone_cell` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL",
            "`name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NOT NULL",
            "`street` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL",
            "`building` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL",
            "`flat` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL",
            "`amount` tinyint(3) unsigned DEFAULT NULL",
            "`comment` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL",
            "`t` time DEFAULT NULL",
            "`sum` mediumint(8) unsigned DEFAULT NULL",
            "`sum_ui` int(8) unsigned DEFAULT NULL",
            "`sum_si` int(8) DEFAULT NULL",
            "`sum_ubi` bigint(8) unsigned DEFAULT NULL",
            "`sum_sbi` bigint(8) DEFAULT NULL",
            "`meeting_start` time DEFAULT NULL",
            "`added` datetime NOT NULL",
            "`added_dt` date DEFAULT NULL",
            "`cancelled_status` enum('active','cancelled','returned','refused','closed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active'",
            "`mes_res` text COLLATE utf8mb4_unicode_ci",
            "`repair_set_price` smallint(5) DEFAULT NULL",
            "`sum_repair2` mediumint(8) DEFAULT NULL",
            "`report_day` tinyint(1) unsigned NOT NULL DEFAULT '0'",
            "`sum1_withwrawed` tinyint(1) NOT NULL DEFAULT '0'"
        ];
        
        $this->assertEquals($expected, $this->object->getFieldsAsSql($this->getSql()));
    }
    
    public function testGetDataSetsDefinitionList()
    {
        $lines = $this->object->getDataSetsDefinitionList($this->getSql());
        $this->assertTrue(is_array($lines));
        $this->assertNotEmpty($lines);
        $this->assertEquals("counter", $lines["id"]);
        $this->assertEquals("integer:min=0;max=255", $lines["report_day"]);
        $this->assertEquals("integer:min=0;max=255", $lines["amount"]);
        $this->assertEquals("integer:min=-128;max=127", $lines["sum1_withwrawed"]);
        $this->assertEquals("integer:min=0;max=65535", $lines["operator_id"]);
        $this->assertEquals("integer:min=-32768;max=32767", $lines["manager_id"]);
        $this->assertEquals("integer:min=-32768;max=32767", $lines["repair_set_price"]);
        $this->assertEquals("integer:min=0;max=16777215", $lines["sum"]);
        $this->assertEquals("integer:min=-8388608;max=8388607", $lines["sum_repair2"]);
        
        $this->assertEquals("integer:min=0;max=" . mt_getrandmax(), $lines["sum_ui"]);
        $this->assertEquals("integer:min=" . (floor((mt_getrandmax()-1)/2)*-1) . ";max=" . floor(mt_getrandmax()/2), $lines["sum_si"]);
        $this->assertEquals("integer:min=0;max=" . mt_getrandmax(), $lines["sum_ubi"]);
        $this->assertEquals("integer:min=" . (floor((mt_getrandmax()-1)/2)*-1) . ";max=" . floor(mt_getrandmax()/2), $lines["sum_sbi"]);
        
        $this->assertEquals("datetime:date_min=1900-01-01;date_max=2099-12-31", $lines["added"]);
        $this->assertEquals("date:min=1900-01-01;max=2099-12-31", $lines["added_dt"]);
        $this->assertEquals("time", $lines["t"]);
        $this->assertEquals("time", $lines["meeting_start"]);
    }
    
    private function getSql()
    {
        return "CREATE TABLE `claim` (
            `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
            `operator_id` smallint(5) unsigned DEFAULT NULL,
            `manager_id` smallint(5) DEFAULT NULL,
            `phone` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `phone_cell` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NOT NULL,
            `street` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `building` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `flat` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `amount` tinyint(3) unsigned DEFAULT NULL,
            `comment` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `t` time DEFAULT NULL,
            `sum` mediumint(8) unsigned DEFAULT NULL,
            `sum_ui` int(8) unsigned DEFAULT NULL,
            `sum_si` int(8) DEFAULT NULL,
            `sum_ubi` bigint(8) unsigned DEFAULT NULL,
            `sum_sbi` bigint(8) DEFAULT NULL,
            `meeting_start` time DEFAULT NULL,
            `added` datetime NOT NULL,
            `added_dt` date DEFAULT NULL,
            `cancelled_status` enum('active','cancelled','returned','refused','closed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
            `mes_res` text COLLATE utf8mb4_unicode_ci,
            `repair_set_price` smallint(5) DEFAULT NULL,
            `sum_repair2` mediumint(8) DEFAULT NULL,
            `report_day` tinyint(1) unsigned NOT NULL DEFAULT '0',
            `sum1_withwrawed` tinyint(1) NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`),
            KEY `added` (`added`),
            KEY `cancelled_status` (`cancelled_status`),
            KEY `city_id` (`city_id`),
            KEY `meeting_finish` (`meeting_finish`),
            KEY `added_dt` (`added_dt`),
            KEY `added_dt_2` (`added_dt`,`cancelled_status`),
            KEY `operator_id` (`operator_id`,`cancelled_status`,`added_dt`),
            KEY `operator_id_2` (`operator_id`,`cancelled_status`,`added_dt`,`meeting_finish`),
            KEY `added_dt_3` (`added_dt`,`city_id`,`cancelled_status`)
           ) ENGINE=InnoDB AUTO_INCREMENT=390766 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
    }
}
