<?php

namespace RandData\Set\ru_RU;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-10 at 01:53:28.
 */
class StreetTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Street
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Street;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Set\ru_RU\Street::get
     */
    public function testGet() {
        $pattern = "/^[АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя\w\s\.-]+\s+(ул|пер)\.$/";
        
        for ($i = 1; $i <= 10; $i++) {
            $this->assertRegExp($pattern, $this->object->get());
        }
    }
}
