<?php

namespace RandData\Generator;

class PersonGenerator extends \RandData\Generator
{
    public function getDataSets() {
        return [
            "Name" => "ru_person",
            "Birth" => "date:min=1900-01-01;max=2005-12-31",
            "Phone" => "phone:country_list=7;region_list=495,499,915,919,905,903",
            "Sum" => "integer:min=100;max=10000",
            "Class" => "string_list:values=aaa,bbb,ccc;possibility=50,20,30"
        ];
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-05 at 14:47:40.
 */
class JsonTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Json
     */
    protected $generator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->generator = new JsonImplementation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Generator\Json::build
     */
    public function testBuild() {
        
    }

    /**
     * @covers RandData\Generator\Json::buildOne
     */
    public function testBuildOne() {
        
    }
}
