<?php

namespace RandData;

class TupleImplementation4 extends Tuple
{
    public function getDataSets() {
        return [
            "integer:min=1;max=100"
        ];
    }
    
    protected function getNullProbability() {
        return [
            50
        ];
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-12 at 21:59:56.
 */
class FormatterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Formatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Formatter(new Generator(new TupleImplementation4()));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Formatter::__construct
     * @covers RandData\Formatter::build
     * @covers RandData\Formatter::buildOne
     * @covers RandData\Formatter::getNullAs
     */
    public function testBuild() {
        
        $data = $this->object->build();
        $this->assertNotEmpty($data);
        $this->assertCount(10, $data);
        
        foreach ($data as $row) {
            $this->assertCount(1, $row);
            $this->assertTrue(array_key_exists(0, $row));

            if (!empty($row[0])) {
                $this->assertTrue($row[0] >= 1);
                $this->assertTrue($row[0] <= 100);
            }
        }        
    }
}
