<?php

namespace RandData;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-12 at 21:59:56.
 */
class FormatterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Formatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Formatter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Formatter::buildOne
     */
    public function testBuildOne() {
        $data1 = [ 1, 2, 3, 4 ];
        $this->assertEquals($data1, $this->object->buildOne(1, $data1));
        $this->assertEquals($data1, $this->object->buildOne(2, $data1));
        $data2 = [ 5, 6, 7, 8, 9, 0 ];
        $this->assertEquals($data2, $this->object->buildOne(1, $data2));
        $this->assertEquals($data2, $this->object->buildOne(6, $data2));
    }

    /**
     * @covers RandData\Formatter::build
     */
    public function testBuild() {
        $data1 = [ 1, 2, 3, 4 ];
        $this->assertEquals($data1, $this->object->build($data1));
        $data2 = [ 5, 6, 7, 8, 9, 0 ];
        $this->assertEquals($data2, $this->object->build($data2));
    }
}
