<?php

namespace RandData\Fabric\Tuple\SqlCreateParser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-24 at 10:17:38.
 */
class CounterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Counter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Counter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Fabric\Tuple\SqlCreateParser\Counter::parse
     */
    public function testParse() {
        $fieldDefinition = "`id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT";
        $this->assertEquals("counter", $this->object->parse($fieldDefinition));
        $this->assertNull($this->object->parse("asdgasdg"));
    }

}
