<?php

namespace RandData\Fabric\Tuple\SqlCreateParser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-24 at 10:20:25.
 */
class DecimalTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Decimal
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Decimal;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Fabric\Tuple\SqlCreateParser\Decimal::parse
     */
    public function testParse() {
        $fieldDefinition = "`salary3` decimal NULL DEFAULT '0'";
        $this->assertEquals("decimal:min=-9999999999;max=9999999999;minFractionDigits=0;maxFractionDigits=0", $this->object->parse($fieldDefinition));
        
        $fieldDefinition2 = "`salary3` decimal(4) NULL DEFAULT '0'";
        $this->assertEquals("decimal:min=-9999;max=9999;minFractionDigits=0;maxFractionDigits=0", $this->object->parse($fieldDefinition2));
        $fieldDefinition3 = "`salary3` decimal(6,2) NULL DEFAULT '0'";
        $this->assertEquals("decimal:min=-9999;max=9999;minFractionDigits=0;maxFractionDigits=2", $this->object->parse($fieldDefinition3));

        $this->assertNull($this->object->parse("asdgasdg"));
    }

}
