<?php

namespace RandData\Fabric\Tuple\SqlCreateParser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-24 at 11:38:31.
 */
class IntTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Integer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Integer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Fabric\Tuple\SqlCreateParser\Integer::parse
     */
    public function testParse() {
        $fieldDefinition = "`report_day` tinyint(3) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-128;max=127", $this->object->parse($fieldDefinition));
        $fieldDefinition2 = "`report_day` tinyint(12) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-128;max=127", $this->object->parse($fieldDefinition2));
        $fieldDefinition3 = "`report_day` tinyint(123) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-128;max=127", $this->object->parse($fieldDefinition3));
        $fieldDefinition4 = "`report_day` smallint(1) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-32768;max=32767", $this->object->parse($fieldDefinition4));
        $fieldDefinition5 = "`report_day` smallint(12) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-32768;max=32767", $this->object->parse($fieldDefinition5));
        $fieldDefinition6 = "`report_day` smallint(123) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-32768;max=32767", $this->object->parse($fieldDefinition6));
        $fieldDefinition7 = "`report_day` mediumint(123) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-8388608;max=8388607", $this->object->parse($fieldDefinition7));
        $fieldDefinition8 = "`report_day` mediumint(12) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-8388608;max=8388607", $this->object->parse($fieldDefinition8));
        $fieldDefinition9 = "`report_day` mediumint(1) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=-8388608;max=8388607", $this->object->parse($fieldDefinition9));
        $fieldDefinition10 = "`report_day` int(9) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=" . (floor((mt_getrandmax()-1)/2)*-1) . ";max=" . floor(mt_getrandmax()/2), $this->object->parse($fieldDefinition10));
        $fieldDefinition11 = "`report_day` bigint(9) NOT NULL DEFAULT '0'";
        $this->assertEquals("integer:min=" . (floor((mt_getrandmax()-1)/2)*-1) . ";max=" . floor(mt_getrandmax()/2), $this->object->parse($fieldDefinition11));
        $this->assertNull($this->object->parse("asdgasdg"));
    }

}
