<?php

namespace RandData\Fabric\Tuple\SqlCreateParser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-24 at 11:52:13.
 */
class StringTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var String
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Str;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Fabric\Tuple\SqlCreateParser\Str::parse
     */
    public function testParse() {
        $fieldDefinition = "`phone` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL";
        $this->assertEquals("string:length_min=1;length_max=100", $this->object->parse($fieldDefinition));
        $fieldDefinition2 = "`phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL";
        $this->assertEquals("string:length_min=1;length_max=255", $this->object->parse($fieldDefinition2));
        $fieldDefinition3 = "enum('one','two','three)";
        $this->assertEquals("string_list:values=one,two,three", $this->object->parse($fieldDefinition3));
        $fieldDefinition4 = "set('one','two','three)";
        $this->assertEquals("string_list:values=one,two,three", $this->object->parse($fieldDefinition4));
        $this->assertNull($this->object->parse("asdgasdg"));
    }

}
