<?php

namespace RandData\Fabric\Tuple\SqlCreateParser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-24 at 11:56:14.
 */
class TextTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Text
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Text;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RandData\Fabric\Tuple\SqlCreateParser\Text::parse
     */
    public function testParse() {
        $fieldDefinition = "`mes_res` tinytext COLLATE utf8mb4_unicode_ci";
        $this->assertEquals("string:length_min=1;length_max=256", $this->object->parse($fieldDefinition));
        
        $fieldDefinition2 = "`mes_res` text COLLATE utf8mb4_unicode_ci";
        $this->assertEquals("string:length_min=1;length_max=65536", $this->object->parse($fieldDefinition2));
        
        $fieldDefinition3 = "`mes_res` mediumtext COLLATE utf8mb4_unicode_ci";
        $this->assertEquals("string:length_min=1;length_max=16777216", $this->object->parse($fieldDefinition3));
        
        $fieldDefinition4 = "`mes_res` longtext COLLATE utf8mb4_unicode_ci";
        $this->assertEquals("string:length_min=1;length_max=16777216", $this->object->parse($fieldDefinition4));
        
        $this->assertNull($this->object->parse("asdgasdg"));
    }

}
